swagger: "2.0"
info:
  description: "T"
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
tags:
- name: "pods"
  description: "access to pods"
schemes:
- "https"
paths:
  /pod:
    get:
      tags:
      - "pods"
      summary: "point of mesures"
      description: ""
      operationId: "getPodContent"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: virtual-id
        description: "the pod identification"
        required: true
        type: string
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/virtual-pod"
              
        405:
          description: "Invalid input"
      security: []
      
    post:
      tags:
      - "pods"
      summary: "" 
      description: ""
      parameters:
      - in: query
        name: virtual-id
        description: "the pod identification"
        required: true
        type: string
      - in: query
        name: contents
        description: "the pod contents, coma separated"
        required: false
        type: string
      responses:
        200:
          description: OK
      security: []
    
    
    put:
      tags:
      - "pods"
      summary: "point of mesures"
      description: ""
      operationId: "setPodContent"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: virtual-id
        description: "the pod identification"
        required: true
        type: string
        
      - in: query
        name: contents
        description: "the pod contents, coma separated"
        required: true
        type: string
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/virtual-pod"
              
        405:
          description: "Invalid input"
      security: []
  
    
definitions:       
        
  virtual-pod:
    type: array
    items:
      type: string
      
externalDocs: 
  description: "Find out more about Swagger"
  url: "http://swagger.io"