swagger: "2.0"
info:
  description: "T"
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
tags:
- name: "pods"
  description: "access to pods"
schemes:
- "https"
paths:
  /pod:
    get:
      tags:
      - "pods"
      summary: "point of mesures"
      description: ""
      operationId: "getPodContent"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: virtual-id
        description: "the pod identification"
        required: true
        type: string
      responses:
        200:
          description: "successful operation"
          schema:
            type: object
            properties:
              content:
                $ref: "#/definitions/virtual-pod"
              
        405:
          description: "Invalid input"
      security: []
    
definitions:
#  mesure:
#    type: object
#    properties:
#      dateTime:
#        type: "string"
#        format: "date-time"
#      value:
#        type: number
#        format: double
#      unite:
#        type: string
#        format: string
        
        
  virtual-pod:
    type: array
    items:
      type: string
      
externalDocs: 
  description: "Find out more about Swagger"
  url: "http://swagger.io"